# Generated by Django 4.2.3 on 2023-10-10 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BooksModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookid', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=500)),
                ('autors', models.CharField(max_length=200)),
                ('average_rating', models.CharField(max_length=100)),
                ('isbn', models.CharField(max_length=100)),
                ('isbn13', models.CharField(max_length=100)),
                ('language_codes', models.CharField(max_length=100)),
                ('num_pages', models.IntegerField()),
                ('ratings_count', models.IntegerField()),
                ('text_reviews_count', models.IntegerField()),
                ('publication_date', models.CharField(max_length=100)),
                ('publisher', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MemberModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memberid', models.CharField(max_length=10)),
                ('member_name', models.CharField(max_length=200)),
                ('Gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('No Active', 'No Active')], max_length=20)),
                ('rent', models.IntegerField()),
                ('book_issue_date', models.DateField(auto_now_add=True)),
                ('bookid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.booksmodel')),
            ],
        ),
    ]
